package com.wd.filemanager.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "filemanager")
public class FileDb {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBRangeKey(attributeName = "user")
    private String user;
    @DynamoDBAttribute(attributeName = "fileName")
    private String fileName;
    @DynamoDBAttribute(attributeName = "s3Url")
    private String s3Url;
    @DynamoDBAttribute(attributeName = "uploadTimestamp")
    private String uploadTimestamp;

}

